---
- name: Query Oracle Database Role and Switchover Status
  hosts: linuxdb
  tasks:
    - name: Source the bash profile and set environment variables
      shell: |
        # Set Environment Variables
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin

        # Run SQL Query
        echo "SELECT inst_id, name, value FROM gv\$dataguard_stats WHERE name='apply lag';" | sqlplus -s / as sysdba
      register: db_status
      ignore_errors: yes

    - name: Check if the SQL query returned "no rows selected"
      set_fact:
        query_result: "{{ 'no rows selected' in db_status.stdout }}"

    - name: Parse the apply lag value from query results
      set_fact:
        apply_lag_value: "{{ (db_status.stdout | regex_search('VALUE\n([^ ]+)', '\\1') | default('0')) }}"

    - name: Determine if the database is ready for switchover
      set_fact:
        switchover_status: >
          {% if query_result %}
            "Database belum siap dilakukan switchover. Tidak ada data apply lag yang ditemukan."
          {% elif apply_lag_value in ['1', '2', '3'] %}
            "Database siap dilakukan switchover."
          {% else %}
            "Database belum siap dilakukan switchover. Apply lag value: {{ apply_lag_value }}"
          {% endif %}

    - name: Display the database status
      debug:
        msg: "Database Status:\n{{ db_status.stdout }}"

    - name: Notify the switchover readiness status
      debug:
        msg: "{{ switchover_status }}"
