---
- name: Query Oracle Database Role and Switchover Status
  hosts: linuxdb
  tasks:
    - name: Source the bash profile and set environment variables
      shell: |
        # Set Environment Variables
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin

        # Run SQL Query
        echo "SELECT inst_id, name, value FROM gv$dataguard_stats WHERE name='apply lag';" | sqlplus -s / as sysdba
      register: db_status
      ignore_errors: yes

    - name: Display raw SQL query result
      debug:
        msg: "Raw SQL Query Result:\n{{ db_status.stdout }}"

    - name: Check if the SQL query returned "no rows selected"
      set_fact:
        query_result: "{{ 'no rows selected' in db_status.stdout }}"

    - name: Extract lag value
      set_fact:
        lag_value: "{{ db_status.stdout | regex_search('VALUE\n(.+)', '\\1') | trim }}"
    
    - name: Display extracted lag value
      debug:
        msg: "Extracted Lag Value: '{{ lag_value }}'"

    - name: Check if the lag value indicates readiness for switchover
      set_fact:
        is_ready_for_switchover: "{{ lag_value == '+00 00:00:00' or lag_value == '+00 00:00:01' or lag_value == '+00 00:00:02' }}"

    - name: Display readiness status
      debug:
        msg: "Is ready for switchover: {{ is_ready_for_switchover }}"

    - name: Notify if the database is ready for switchover
      debug:
        msg: "Database siap dilakukan switchover."
      when: is_ready_for_switchover and not query_result

    - name: Notify if the database is not ready for switchover
      debug:
        msg: "Database belum siap dilakukan switchover."
      when: not is_ready_for_switchover and not query_result

    - name: Notify if no rows were selected
      debug:
        msg: "No rows were selected, query executed successfully."
      when: query_result
