---
- name: Query Oracle Database Role and Switchover Status
  hosts: ora19cdg02.bwok.org
  tasks:
    - name: Source the bash profile and set environment variables
      shell: |
        # Set Environment Variables
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin

        # Run SQL Query
        echo "SELECT database_role, switchover_status FROM v\$database;" | sqlplus -s / as sysdba
      register: db_status
      ignore_errors: yes

    - name: Display the database status
      debug:
        msg: "Database Status:\n{{ db_status.stdout }}"

    - name: Check if switchover_status contains 'TO PRIMARY'
      set_fact:
        need_switchover: "{{ 'TO PRIMARY' in db_status.stdout }}"

    - name: Perform switchover to primary if needed
      shell: |
        # Set Environment Variables
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin

        # Execute Switchover Command
        echo "ALTER DATABASE COMMIT TO SWITCHOVER TO PRIMARY;" | sqlplus -s / as sysdba
      when: need_switchover
      register: switchover_result

    - name: Display switchover result
      debug:
        msg: "Switchover Result:\n{{ switchover_result.stdout }}"
      when: need_switchover

    - name: Fail if switchover is needed but not performed
      fail:
        msg: "Switchover to primary was required but not performed."
      when: not need_switchover and 'TO PRIMARY' in db_status.stdout
